export class MenuLabelsConstant {
  keywords: string[];
  name: string;
  class: string;
  disabled: boolean;
  blink: boolean;
}

export const MenuLabels: MenuLabelsConstant[] = [
   { keywords: ['m_grey_large', 'a_grey_large', 'i_grey_large', 'n_grey_large', 'no_image_grey_large', 'm_grey_large', 'e_grey_large', 'n_grey_large', 'u_grey_large'], name: 'main menu', disabled: false, blink: false, class: 'mainmenu'},
   { keywords: ['n_brown_medium', 'e_brown_medium', 'w_brown_medium', 'no_image_brown_medium', 'g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'new game', disabled: false, blink: true, class: 'newgame'},
   { keywords: ['s_brown_medium', 'a_brown_medium', 'v_brown_medium', 'e_brown_medium', 'no_image_brown_medium', 'g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'save game', disabled: true, blink: true, class: 'savegame' },
   { keywords: ['l_brown_medium', 'o_brown_medium', 'a_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 'g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'load game', disabled: false, blink: true, class: 'loadgame' },
   { keywords: ['o_brown_medium', 'p_brown_medium', 't_brown_medium', 'i_brown_medium', 'o_brown_medium', 'n_brown_medium', 's_brown_medium'], name: 'options', disabled: false, blink: true, class: 'options' },
   { keywords: ['c_brown_medium', 'r_brown_medium', 'e_brown_medium', 'd_brown_medium', 'i_brown_medium', 't_brown_medium', 's_brown_medium'], name: 'credits', disabled: false, blink: true, class: 'credits' },
   { keywords: ['h_brown_medium', 'e_brown_medium', 'l_brown_medium', 'p_brown_medium'], name: 'help', disabled: false, blink: true, class: 'help' },
   { keywords: ['q_brown_medium', 'u_brown_medium', 'i_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'quit game', disabled: false, blink: true, class: 'quitmenu' },
];

export const NewGameLabels: MenuLabelsConstant[] = [
   { keywords: ['n_grey_large', 'e_grey_large', 'w_grey_large', 'no_image_brown_medium' , 'g_grey_large', 'a_grey_large', 'm_grey_large', 'e_grey_large'], name: 'new game', disabled: false, blink: false, class: 'newgame' },
   { keywords: ['s_brown_medium', 'i_brown_medium', 'n_brown_medium', 'g_brown_medium', 'l_brown_medium', 'e_brown_medium', 'no_image_brown_medium', 'p_brown_medium', 'l_brown_medium', 'a_brown_medium', 'y_brown_medium', 'e_brown_medium', 'r_brown_medium'], name: 'user profile', disabled: false, blink: true, class: 'profile' },
   { keywords: ['m_brown_medium', 'u_brown_medium', 'l_brown_medium', 't_brown_medium', 'i_brown_medium', 'p_brown_medium', 'l_brown_medium', 'a_brown_medium', 'y_brown_medium', 'e_brown_medium', 'r_brown_medium', 'no_image_brown_medium', 'g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'multiplayer game', disabled: false, blink: true, class: 'multiplayer' },
   { keywords: ['t_brown_medium', 'u_brown_medium', 't_brown_medium', 'o_brown_medium', 'r_brown_medium', 'i_brown_medium', 'a_brown_medium', 'l_brown_medium', 's_brown_medium'], name: 'tutorials', disabled: false, blink: true, class: 'tutorials' },
   { keywords: ['r_brown_medium', 'e_brown_medium', 's_brown_medium', 't_brown_medium', 'a_brown_medium', 'r_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'm_brown_medium', 'i_brown_medium', 's_brown_medium', 's_brown_medium', 'o_brown_medium', 'n_brown_medium'], name: 'restart mission', disabled: false, blink: true, class: 'restart' },
   { keywords: ['l_brown_medium', 'o_brown_medium', 'a_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 'q_brown_medium', 'u_brown_medium', 'i_brown_medium', 'c_brown_medium', 'k_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'a_brown_medium', 'v_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 'g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium' ], name: 'load quick saved game', disabled: true, blink: false, class: 'loadquicksave' },
   { keywords: ['p_brown_medium', 'a_brown_medium', 's_brown_medium', 's_brown_medium','w_brown_medium', 'o_brown_medium', 'r_brown_medium', 'd_brown_medium'], name: 'password', disabled: false, blink: true, class: 'password' }
];

export const LoadGameLabels: MenuLabelsConstant[] = [
   { keywords: ['l_grey_large', 'o_grey_large', 'a_grey_large', 'd_grey_large', 'no_image_brown_medium', 'g_grey_large', 'a_grey_large', 'm_grey_large', 'e_grey_large'], name: 'load game', disabled: false, blink: false, class: 'loadgame' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium',  'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium','no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' },
   { keywords: ['hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'no_image_brown_medium', 'u_brown_medium', 'n_brown_medium', 'u_brown_medium', 's_brown_medium', 'e_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'l_brown_medium', 'o_brown_medium', 't_brown_medium', 'no_image_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium', 'hyphen_brown_medium'], name: 'unsued slot', disabled: false, blink: true, class: 'unsuedslot' }
];

export const OptionsLabels: MenuLabelsConstant[] = [
   { keywords: ['o_grey_large', 'p_grey_large', 't_grey_large', 'i_grey_large', 'o_grey_large', 'n_grey_large', 's_grey_large'], name: 'options', disabled: false, blink: false, class: 'options' },
   { keywords: ['u_brown_medium', 's_brown_medium', 'e_brown_medium', 'r_brown_medium', 'no_image_brown_medium', 'p_brown_medium', 'r_brown_medium', 'o_brown_medium', 'f_brown_medium', 'i_brown_medium', 'l_brown_medium', 'e_brown_medium', 'no_image_brown_medium'], name: 'user profile', disabled: false, blink: true, class: 'profile' },
   { keywords: ['s_brown_medium', 'o_brown_medium', 'u_brown_medium', 'n_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 'v_brown_medium', 'o_brown_medium', 'l_brown_medium', 'u_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'sound', disabled: false, blink: true, class: 'vloume' },
   { keywords: ['audiobar', 'audioslider'], name: 'volume bar', disabled: false, blink: false, class: 'volumebar' },
   { keywords: ['v_brown_medium', 'i_brown_medium', 'd_brown_medium', 'e_brown_medium', 'o_brown_medium', 'no_image_brown_medium', 'o_brown_medium', 'p_brown_medium', 't_brown_medium', 'i_brown_medium', 'o_brown_medium', 'n_brown_medium', 's_brown_medium'], name: 'video options', disabled: false, blink: true, class: 'videos' },
   { keywords: ['g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium', 'no_image_brown_medium', 'p_brown_medium', 'r_brown_medium', 'e_brown_medium', 'f_brown_medium', 'e_brown_medium', 'r_brown_medium', 'e_brown_medium', 'n_brown_medium', 'c_brown_medium', 'e_brown_medium', 's_brown_medium'], name: 'game preferences', disabled: false, blink: true, class: 'preferences' },
   { keywords: ['e_brown_medium', 'x_brown_medium', 'i_brown_medium', 't_brown_medium'], name: 'exit', disabled: false, blink: true, class: 'exit' }
];

// export const HelpLabels: MenuLabelsConstant[] = [
//    { keywords: ['o_grey_large', 'p_grey_large', 't_grey_large', 'i_grey_large', 'o_grey_large', 'n_grey_large', 's_grey_large'], name: 'options', disabled: false, blink: true, class: 'options' },
//    { keywords: ['u_brown_medium', 's_brown_medium', 'e_brown_medium', 'r_brown_medium', 'no_image_brown_medium', 'p_brown_medium', 'r_brown_medium', 'o_brown_medium', 'f_brown_medium', 'i_brown_medium', 'l_brown_medium', 'e_brown_medium', 'no_image_brown_medium'], name: 'user profile', disabled: false, blink: true, class: 'profile' },
//    { keywords: ['s_brown_medium', 'o_brown_medium', 'u_brown_medium', 'n_brown_medium', 'd_brown_medium', 'no_image_brown_medium', 'v_brown_medium', 'o_brown_medium', 'l_brown_medium', 'u_brown_medium', 'm_brown_medium', 'e_brown_medium'], name: 'sound', disabled: false, blink: true, class: 'vloume' },
//    { keywords: ['no_image_brown_medium'], name: 'volume bar', disabled: false, blink: true, class: 'volumebar' },
//    { keywords: ['v_brown_medium', 'i_brown_medium', 'd_brown_medium', 'e_brown_medium', 'o_brown_medium', 'no_image_brown_medium', 'o_brown_medium', 'p_brown_medium', 't_brown_medium', 'i_brown_medium', 'o_brown_medium', 'n_brown_medium', 's_brown_medium'], name: 'video options', disabled: false, blink: true, class: 'videos' },
//    { keywords: ['g_brown_medium', 'a_brown_medium', 'm_brown_medium', 'e_brown_medium', 'no_image_brown_medium', 'p_brown_medium', 'r_brown_medium', 'e_brown_medium', 'f_brown_medium', 'e_brown_medium', 'r_brown_medium', 'e_brown_medium', 'n_brown_medium', 'c_brown_medium', 'e_brown_medium', 's_brown_medium'], name: 'game preferences', disabled: false, blink: true, class: 'preferences' },
//    { keywords: ['e_brown_medium', 'x_brown_medium', 'i_brown_medium', 't_brown_medium'], name: 'exit', disabled: false, blink: true, class: 'exit' }
// ];

export const QuitGameLabels: MenuLabelsConstant[] = [
   { keywords: ['q_grey_large', 'u_grey_large', 'i_grey_large', 't_grey_large', 'no_image_brown_medium', 'g_grey_large', 'a_grey_large', 'm_grey_large', 'e_grey_large'], name: 'options', disabled: false, blink: false, class: 'options' },
   { keywords: ['a_brown_medium', 'r_brown_medium', 'e_brown_medium', 'no_image_brown_medium', 'y_brown_medium', 'o_brown_medium', 'u_brown_medium', 'no_image_brown_medium', 's_brown_medium', 'u_brown_medium', 'r_brown_medium', 'e_brown_medium', 'no_image_brown_medium', 'y_brown_medium', 'o_brown_medium', 'u_brown_medium', 'no_image_brown_medium', 'w_brown_medium', 'a_brown_medium', 'n_brown_medium', 't_brown_medium', 'no_image_brown_medium', 't_brown_medium', 'o_brown_medium', 'no_image_brown_medium', 'q_brown_medium', 'u_brown_medium', 'i_brown_medium', 't_brown_medium'], name: 'quit confirmation', disabled: false, blink: true, class: 'quitconfirmation' },
   { keywords: ['y_brown_medium', 'e_brown_medium', 's_brown_medium', 'no_image_brown_medium', 'no_image_brown_medium', 'no_image_brown_medium', 'n_brown_medium', 'o_brown_medium'], name: 'quit options', disabled: false, blink: true, class: 'quitoptions' }
];